name: model-supervisé RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA : ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Your ML workflow goes here
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AA16FCBCA621E701
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EFFAF4443CE9AD84
          apt-get update
          pip install -r requirements.txt
          dvc pull boston.csv
          python Boston_regression.py
          # Write your CML report
          echo "## Metriques:" >> report.md
          cat metrics.txt >> report.md
          git config --global user.email "marzaq6@gmail.com"
          git config --global user.name "MarzaqMed"
          git add report.md metrics.txt
          git commit -m "reports"
          git fetch
          git push 
