name: model-supervisé RL

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-dev
          pip install pygit2
          pip install -r requirements.txt
          pip install dvc==2.5.4
          pip install 'dvc[gdrive]'

      - name: Pull DVC data
        run: dvc pull boston.csv

      - name: Run ML script
        run: python Boston_regression.py

      - name: Generate CML report
        run: |
          echo "## Metriques:" >> report.md
          cat metrics.txt >> report.md
          git config --global user.email "marzaq6@gmail.com"
          git config --global user.name "MarzaqMed"
          git add report.md metrics.txt
          git commit -m "Add reports"
          git push
