name: model-supervisé RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python Boston_regression.py
          # Write your CML report
          echo "## Metriques:" >> report.md
          cat metrics.txt >> report.md
          git config --global user.email "marzaq6@gmail.com"
          git config --global user.name "MarzaqMed"
          git add report.md metrics.txt
          git commit -m "reports"
          git fetch
          git push 
