name: model-supervisé RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

        run: |
          # Your ML workflow goes here
          cp default.json /github/home/.cache/pydrive2fs/543037340815-5spc6gs2clbe239ubbf9h71ifqqgu302.apps.googleusercontent.com/default.json 
          pip install -r requirements.txt
          dvc pull
          python Boston_regression.py
          # Write your CML report
          echo "## Metriques:" >> report.md
          cat metrics.txt >> report.md
          git config --global user.email "datafylt@gmail.com"
          git config --global user.name "datafylt"
          git add report.md metrics.txt
          git commit -m "reports"
          git fetch
          git push 
